# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A prototype function that runs the inla function and
#' returns the marginal log-likelihood
#' @return inla_results the marginal log likelihood
#' @useDynLib BARTSIMP, .registration = TRUE
#' @param s1 a vector containing the longitude data
#' @param s2 a vector containing the latitude data
#' @param y the response variable
#' @importFrom Rcpp sourceCpp
#' @return The marginal likelihood for the model
#'
#' @examples
#' \dontrun{
#' s1 <- c(0, 0.5, 1)
#' s2 <- c(0, 0.5, 1)
#' y <- c(1.2, 0.8, 1.5)
#' mySPDE(s1, s2, y)
#' }
#'
#' @export
mySPDE <- function(s1, s2, y) {
    .Call(`_BARTSIMP_mySPDE`, s1, s2, y)
}

#' @export
makeC <- function(idv, n) {
    .Call(`_BARTSIMP_makeC`, idv, n)
}

#' @export
convertC <- function(mat) {
    .Call(`_BARTSIMP_convertC`, mat)
}

testDFtoNM <- function(x) {
    .Call(`_BARTSIMP_testDFtoNM`, x)
}

#' @export
callPrint <- function(x) {
    invisible(.Call(`_BARTSIMP_callPrint`, x))
}

useOperatorOnVector <- function(x) {
    invisible(.Call(`_BARTSIMP_useOperatorOnVector`, x))
}

useOperatorOnMatrix <- function(x) {
    invisible(.Call(`_BARTSIMP_useOperatorOnMatrix`, x))
}

#' @export
test <- function(s1, s2, ydata) {
    .Call(`_BARTSIMP_test`, s1, s2, ydata)
}

#' @export
test2 <- function(mydf) {
    .Call(`_BARTSIMP_test2`, mydf)
}

#' Multiply a number by two
#'
#' @useDynLib BARTSIMP, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @return Integer value `0`, invisibly printing diagnostic information from
#'   the native tree test routine.
#'
#' @examples
#' timesTwo()
#'
#' @export
timesTwo <- function() {
    .Call(`_BARTSIMP_timesTwo`)
}

